# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.cache/wt} [current_project]
set_property parent.project_path {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Voice_Scope_TOP.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Freq_To_Clk_Divider.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Clk_Div.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Slow_Clocks.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/VOICE_CAPTURER.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/TestWave_Gen.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Volume_Converter.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Waveform_Select.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/VGA_DISPLAY.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Menu_Config.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Debounce_Circuit.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/D_Flip_Flop.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Buttons_Debounce.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Leds_Config.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Seg_Config.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Disp_Config.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Leds_Array.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Seg_Lut.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Seg_Mux.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Seg_Display.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Background.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Background_Mux.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Grid_Mux.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Waveform.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Normal_Waveform.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Bar_Waveform.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Circle_Waveform.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Vol_History.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Menu.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Vga_Menu.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Menu_Pointer.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Main_Menu.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Seg_Menu.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Leds_Menu.v}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Draw_Menu_Background.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/VGA_CONTROL.vhd}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/CLK_108M.vhd}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/font_rom.vhd}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/Pixel_On_Text2.vhd}
  {C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/sources_1/new/commonPak.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KH/Documents/KH/NUS/EE2026/LAB/Lab Project/Final V3/Real-Time Voice Scope/Real-Time Voice Scope.srcs/constrs_1/new/constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Voice_Scope_TOP -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voice_Scope_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voice_Scope_TOP_utilization_synth.rpt -pb Voice_Scope_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
